
def fail(string: str) -> None: # Failure
	print("[ERROR] "+str(string))
	exit(1)


